/* global describe, before, it, data */

describe('Thumbnail image', function () {
  var thumbnail = null
  var thumbnail_alt = null

  before(function () {
    if (!data.meta['gcOGImage'] && !data.meta.alt['gcOGImage']) {
      this.skip() // Skip if thumbnails are not set
    }

    thumbnail = data.meta['gcOGImage']
    thumbnail_alt = data.meta.alt['gcOGImage']
  })

  it('should have thumbnail image set on both languages', function () {
    data.meta.should.have.own.property('gcOGImage')
    data.meta.alt.should.have.own.property('gcOGImage')
  })

  it('should be the same thumbnail for both languages', function () {
    try {
      data.meta['gcOGImage'].should.equal(data.meta.alt['gcOGImage'])
    } catch (e) {
      this.skip() // Warning only
    }
  })

  it('Path must start with <code>/content/dam/</code>', function () {
    data.meta['gcOGImage'].should.match(/^\/content\/dam\//)
  })

  describe('Path', function () {
    it('within the maple-leaf folder', function () {
      // All images should be stored in the same folder in the DAM
      thumbnail.should.have.string('/content/dam/dnd-mdn/images/maple-leaf/articles/')
    })

    it('organized into <code>/{year}/{month}/</code> folders', function () {
      // Year and month folders for organization
      thumbnail.should.match(/maple-leaf\/articles\/\d{4}\/\d{2}\//)
    })

    it('does not contain spaces', function () {
      // There are problems linking to images with spaces in the file name
      thumbnail.should.not.have.string('%20')
    })

    it('is direct link', function () {
      // Images coppied from within the article are dynamically generated by AEM
      thumbnail.should.not.have.string('/_jcr_content/')
    })

    

    it('Path should be structured properly <code>/articles/{YEAR}/{MONTH}/</code>', function () {
      thumbnail.should.match(/^\/content\/dam\/dnd-mdn\/images\/maple-leaf\/articles\/\d{4}\/\d{2}\//)
    })

    it('wtregr')
  })

})
